--- 
javascripts: 
- proto:
  - prototype
  - effects
  - dragdrop
  - controls
- rest: 
  - jquery-1.4.2.min
  - jquery-ui-1.8.5.custom.min
  - application
  - facebox

stylesheets: 
- base:
  - application
  - jquery-ui-1.8.5.custom
  - facebox