production:
  :enable_starttls_auto: false
  :address: caniafforditnow.com
  :domain: caniafforditnow.com
  :port: 25
  :authentication: :plain
  :user_name: hariis@caniafforditnow.com
  :password: mount^hood
