production:
  :enable_starttls_auto: true
  :address: caniafforditnow.com
  :domain: caniafforditnow.com
  :port: 25
  :authentication: :login
  :user_name: hariis@caniafforditnow.com
  :password: mount^hood
